# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "carter"
  s.version = "0.6.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Louis Gillies"]
  s.date = "2011-11-10"
  s.description = "A really simple shopping cart implementation for rails."
  s.email = "louisgillies@ygmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "app/controllers/cart_items_controller.rb",
    "app/controllers/carts_controller.rb",
    "app/models/cart.rb",
    "app/models/cart_item.rb",
    "app/views/carts/show.html.erb",
    "config/routes.rb",
    "generators/carter_generator.rb",
    "generators/carter_install_generator.rb",
    "generators/templates/migration.rb",
    "lib/carter.rb",
    "lib/carter/active_record/extensions.rb",
    "lib/carter/cart.rb",
    "lib/carter/cartable.rb",
    "lib/carter/controller_additions.rb",
    "lib/carter/controller_resource.rb",
    "lib/carter/engine.rb",
    "lib/carter/errors.rb",
    "lib/carter/errors/multiple_cart_items_not_allowed.rb",
    "lib/carter/errors/setup_error.rb",
    "lib/carter/initializer.rb",
    "lib/carter/rails/init.rb",
    "lib/carter/routing.rb",
    "lib/carter/state_machine.rb",
    "lib/tasks/carter.rake"
  ]
  s.homepage = "http://github.com/gillies-dunlop/carter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A really simple shopping cart implementation for rails."
  s.test_files = [
    "spec/active_record/cart_item_spec.rb",
    "spec/active_record/cart_spec.rb",
    "spec/active_record/cartable_spec.rb",
    "spec/app/controllers/cart_items_controller_spec.rb",
    "spec/carter_spec.rb",
    "spec/spec_helper.rb",
    "spec/state_machine_spec.rb",
    "spec/support/active_record_helper.rb",
    "spec/support/factories.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<state_machine>, ["= 1.0.2"])
      s.add_development_dependency(%q<money>, ["= 3.1.5"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<state_machine>, ["= 1.0.2"])
      s.add_dependency(%q<money>, ["= 3.1.5"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<state_machine>, ["= 1.0.2"])
    s.add_dependency(%q<money>, ["= 3.1.5"])
  end
end

